config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    enum status: %w[Prestado Estante]
    validates :title, :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :set_book, only: %i[show]
  before_action :set_selects, only: %i[new create]

  def index
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true)
  end

  def new
    @book = Book.new
  end

  def show
  end

  def create
    @book = Book.create(book_params)
    respond_to do |format|
      if @book.save
        format.html {redirect_to @book, notice: "El libro #{@book.title} se creó exitosamente"}
      else
        format.html {render :new}
      end
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :status, :lending_date, :return_date)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def set_selects
    @statuses = Book.statuses.keys
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h1>El libro "<%= book.title %>" no se agregó por las siguientes razones:</h1>
      <ul>
      <% book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <strong><%= f.label :title, "Título" %></strong>
    <%= f.text_field :title, placeholder: "Ingrese el título", class: 'form-control' %>
  </div>

  <div class="form-group">
    <strong><%= f.label :author, "Autor" %></strong>
    <%= f.text_field :author, placeholder: "Ingrese el autor", class: 'form-control' %>
  </div>

  <div class="form-group">
    <strong><%= f.label :status, "Estado" %></strong><br>
    <%= f.select :status, options_for_select(@statuses), class: 'form-control' %>
  </div>

  <div class="form-group">
    <strong><%= f.label :lending_date, "Fecha de préstamo" %></strong>
    <%= f.date_field :lending_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <strong><%= f.label :return_date,"Fecha de devolución" %></strong>
    <%= f.date_field :return_date, class: 'form-control' %>
  </div>

  <div class='actions'>
    <%= submit_tag "Crear Libro", class: 'btn btn-success' %>
    <%= link_to 'Ver Biblioteca', root_path, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/books/index.html.erb
<%= render 'shared/navbar' %>
<p id="notice"><%= notice %></p>

<h1>Mi Biblioteca</h1>

<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th><%= sort_link(@q, :title, "Título") %></th>
        <th>Autor</th>
        <th>Estado</th>
        <th>Fecha de préstamo</th>
        <th>Fecha de devolución</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.status %></td>
          <td><%= book.lending_date %></td>
          <td><%= book.return_date %></td>
          <td><%= link_to 'Ver', book %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'Nuevo Libro', new_book_path %>

app/views/books/new.html.erb
<%= render 'form', book: @book %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Libro</h1>
<p>
  <strong>Título: </strong>
  <%= @book.title %>
</p>
<p>
  <strong>Autor: </strong>
  <%= @book.author %>
</p>
<p>
  <strong>Estado: </strong>
  <%= @book.status %>
</p>
<p>
  <strong>Fecha de préstamo: </strong>
  <%= @book.lending_date %>
</p>
<p>
  <strong>Fecha de devolución: </strong>
  <%= @book.return_date %>
</p>

<%= link_to 'Volver', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biblioteca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand"></a>
  <%= search_form_for @q do |f|%>
    <div class="form-group form-inline my-2 my-lg-0">
      <%= f.select :status_eq, options_for_select(Book.statuses, @q.status_eq), {}, {class: 'form-control mx-2'} %>
      <%= f.submit 'Filtrar', class: 'btn btn-primary' %>
    </div>
  <% end %>
</nav>